version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: student-mongo
    ports:
      - "27017:27017" # host:container
    volumes:
      - ./mongodbdata:/data/db # host:container
